backend:
  name: github
  repo: amanashutosh6998/ebony-ivory-gallery
  branch: main
  auth_scope: repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "src/content/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
